name: Update SVG with GitHub Data

on:
  schedule:
    - cron: '0 * * * *' # Chaque heure
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get GitHub Repo Info
      id: repo_info
      run: |
        STARS=$(curl -s https://api.github.com/repos/alexisseurin | jq .stargazers_count)
        echo "stars=$STARS" >> $GITHUB_ENV

    - name: Update SVG
      run: |
        sed -i "s/<tspan id=\"stars\">.*<\/tspan>/<tspan id=\"stars\">${{ env.stars }}<\/tspan>/" welcome.svg
    
    - name: Commit and Push Changes
      run: |
        git config --local user.email "alexis.seurin@gmail.com"
        git config --local user.name "Alexis Seurin"
        git add welcome.svg
        git commit -m "Update SVG with latest GitHub data"
        git push

    - name: Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        git push https://alexisseurin:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/alexisseurin/alexisseurin.git HEAD:main
