name: Update SVG with GitHub Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get GitHub Repo Info
      id: repo_info
      run: |
        STARS=$(curl -s https://api.github.com/repos/alexisseurin/public-transport-map | jq .stargazers_count)
        echo "stars=$STARS" >> $GITHUB_ENV

    - name: Update SVG
      run: |
        sed -i "s/<tspan id=\"stars\">.*<\/tspan>/<tspan id=\"stars\">${{ env.stars }}<\/tspan>/" bento.svg

    - name: Check for changes
      id: check_changes
      run: |
        git config --local user.email "alexis.seurin@gmail.com"
        git config --local user.name "Alexis Seurin"
        git add bento.svg
        if git diff --cached --exit-code --quiet; then
          echo "no_changes=true" >> $GITHUB_ENV
        else
          echo "no_changes=false" >> $GITHUB_ENV
        fi
  
    - name: Commit Changes
      if: env.no_changes == 'false'
      run: |
        git commit -m "Update SVG with latest GitHub data"
    
    - name: Push Changes
      if: env.no_changes == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD:main
    
    
